### ISSUE TITLE
Get-CommandInfo not working 🤔

### ISSUE THREAD

**Issue by springcomp** [brettmillerb/Toolbox#4]
@brettmillerb  I have seen a reference to this repository on [Twitter](https://twitter.com/BrettMiller_IT/status/1446480775776509952?s=20)n

I would love to use this `Get-Syntax` command but I’m unable to make it work on my systems.
I have tried:

- Windows PowerShell 5.x
- PowerShell Core 7.1.x
- Powershell Code Daily 7.2.x

Both on Windows and WSL Ubuntu.
Maybe I’m missing something obvious?

Any feedback appreciated.
Sincerely.

**Comment by brettmillerb** [comment]
Hi @springcomp 

`Get-Syntax` utilises `Get-CommandInfo` so you need both functions available to use `Get-Syntax`

I'm using this on a preview version of 7.2.x and a colleague is using the same code in windows terminal on his Windows machine which also works fine afaik.

If you can provide more information on how it is not working I can try and assist though.

**Comment by springcomp** [comment]
@brettmillerb Thanks ever so much for the feedback.

Well, to be precise, I get an error saying that the `Get-CommandInfo` is not a known CmdLet.
It may be just that I don’t know how to find it or install it from 🤷‍♂️

**Comment by brettmillerb** [comment]
> @brettmillerb Thanks ever so much for the feedback.
> 
> Well, to be precise, I get an error saying that the `Get-CommandInfo` is not a known CmdLet. It may be just that I don’t know how to find it or install it from 🤷‍♂️

Hi @springcomp 

In order to use `Get-Syntax` you will also need to have the `Get-CommandInfo` function available as it uses this as an internal/private function.

The `Get-CommandInfo` function is in the same Toolbox module:

https://github.com/brettmillerb/Toolbox/blob/master/Public/Get-CommandInfo.ps1

**Comment by springcomp** [comment]
@brettmillerb I feel embarrassed 🤦‍♂️.
Thank you so much for pointing me in the direction.
Of course, I should have thought this was a private cmdlet of yours.

Cheers.
